version: "3"

networks:
  grafana:

services:
  app:
    build: ./app
    ports:
      - 8081:80
    volumes:
      - ./logs:/var/log
    networks:
      - grafana

  db:
    image: grafana/tns-db:latest
    ports:
      - 8082:80
    networks:
      - grafana
